name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive' # Checkout submodules (like Unity)

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc g++

    - name: Configure CMake
      run: cmake -B build/host -S . -DBUILD_FOR_PICO=OFF

    - name: Build
      run: cmake --build build/host

    - name: Run tests
      run: ./build/host/run_tests
